services:
  proof-server:
    container_name: "midnames-proof-server"
    image: "midnight-proof-server:prebaked"
    command: ["midnight-proof-server -v --network testnet"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
